version: "3.9"
services:
  keycloak_ifood:
    image: jboss/keycloak:14.0.0
    container_name: keycloak_ifood
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=1q2w3e
      - DB_VENDOR=POSTGRES
      - DB_ADDR=pgsql-keycloak
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=1q2w3e
      - KEYCLOAK_LOGLEVEL=INFO
      - ROOT_LOGLEVEL=INFO
    ports:
      - "8180:8080"
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config

  jaeger_ifood:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_ifood
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  activemq_ifood:
    image: vromero/activemq-artemis:2.11.0
    container_name: activemq_ifood
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "5672:5672"
      - "8161:8161"
    volumes:
      - ./activemq_ifood/persistent/dir/conf:/opt/activemq/conf
      - ./activemq_ifood/persistent/dir/data:/opt/activemq/data

networks:
  default:
    external: true
    name: net-ifood