version: "3.9"
services:
  keycloak_ifood:
    image: jboss/keycloak:14.0.0
    container_name: keycloak_ifood
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=1q2w3e
      - DB_VENDOR=POSTGRES
      - DB_ADDR=pgsql-keycloak
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=1q2w3e
      - KEYCLOAK_LOGLEVEL=INFO
      - ROOT_LOGLEVEL=INFO
    ports:
      - "8180:8080"
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config

  jaeger_ifood:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_ifood
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  activemq_ifood:
    image: vromero/activemq-artemis:2.11.0
    container_name: activemq_ifood
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "5672:5672"
      - "8161:8161"
    volumes:
      - ./activemq_ifood/persistent/dir/conf:/opt/activemq/conf
      - ./activemq_ifood/persistent/dir/data:/opt/activemq/data

  zookeeper-ifood:
    image: confluentinc/cp-zookeeper:5.5.6-1-ubi8
    container_name: "zookeeper-ifood"
    hostname: "zookeeper-ifood"
    restart: on-failure
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
        ZOOKEEPER_SERVER_ID: 1
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_INIT_LIMIT: 5
        ZOOKEEPER_SYNC_LIMIT: 5
  kafka-node-ifood:
    container_name: kafka-node-ifood
    image: debezium/kafka:1.1
    ports:
     - 9192:9092
    links:
     - zookeeper-ifood
    environment:
     - ZOOKEEPER_CONNECT=zookeeper-ifood:2181
  kafdrop-ifood:
    image: obsidiandynamics/kafdrop:latest
    container_name: "kafdrop-ifood"
    hostname: "kafdrop-ifood"
    restart: "no"
    ports:
      - "9000:9000"
    depends_on:
      - kafka-node-ifood
    links:
      - "kafka-node-ifood:kafka-node-ifood"
    environment:
      KAFKA_BROKERCONNECT: kafka-node-ifood:9092

networks:
  default:
    external: true
    name: net-ifood