version: "3.9"
services:
  pgsql:
    image: postgres:13.3-alpine
    container_name: pgsql-13
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgsqlconf:/etc/postgresql"
      - "pgsqldata:/var/lib/postgresql/data"
      - "pgsqldblogs:/var/log"
      - "./data:/opt/dump"
    networks:
      - netdbpgsql
  
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-4
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=112358
    ports:
      - "5050:80"
    volumes:
      - "pgadmin4sessiondata:/var/lib/pgadmin"
      - "pgadmin4conf:/pgadmin4/config_local.py"
      - "pgadmin4serverdefinitions:/pgadmin4/servers.json"
    depends_on:
      - pgsql
    networks:
      - netdbpgsql

  keycloak_ifood:
    image: jboss/keycloak:14.0.0
    container_name: keycloak_ifood
    restart: on-failure
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_VENDOR=POSTGRES
      - DB_ADDR=pgsql-13
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_LOGLEVEL=INFO
      - ROOT_LOGLEVEL=INFO
    ports:
      - "8180:8080"
    depends_on:
      - pgsql
    networks:
      - netdbpgsql

  jaeger_ifood:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_ifood
    restart: on-failure
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    depends_on:
      - pgsql
    networks:
      - netdbpgsql

volumes:
  pgsqlconf:
  pgsqldata:
  pgsqldblogs:
  pgadmin4sessiondata:
  pgadmin4conf:
  pgadmin4serverdefinitions:

networks:
  netdbpgsql: