version: "3.9"
services:
  pgsql-cadastro:
    image: postgres:13.3-alpine
    container_name: pgsql-cadastro
    restart: on-failure
    environment:
      - POSTGRES_USER=ifood_cadastro
      - POSTGRES_PASSWORD=1q2w3e
    ports:
      - "5432:5432"
    volumes:
      - "pgsqlconfCadastro:/etc/postgresql"
      - "pgsqldataCadastro:/var/lib/postgresql/data"
      - "pgsqldblogsCadastro:/var/log"
  pgsql-marketplace:
    image: postgres:13.3-alpine
    container_name: pgsql-marketplace
    restart: on-failure
    environment:
      - POSTGRES_USER=ifood_marketplace
      - POSTGRES_PASSWORD=1q2w3e
    ports:
      - "5433:5432"
    volumes:
      - "pgsqlconfMarketplace:/etc/postgresql"
      - "pgsqldataMarketplace:/var/lib/postgresql/data"
      - "pgsqldblogsMarketplace:/var/log"
  pgsql-keycloak:
    image: postgres:13.3-alpine
    container_name: pgsql-keycloak
    restart: on-failure
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=1q2w3e
    ports:
      - "5434:5432"
    volumes:
      - "pgsqlconfKeycloak:/etc/postgresql"
      - "pgsqldataKeycloak:/var/lib/postgresql/data"
      - "pgsqldblogsKeycloak:/var/log"
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-4
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=112358
    ports:
      - "5050:80"
    volumes:
      - "pgadmin4sessiondata:/var/lib/pgadmin"
      - "pgadmin4conf:/pgadmin4/config_local.py"
      - "pgadmin4serverdefinitions:/pgadmin4/servers.json"
    depends_on:
      - pgsql-cadastro
      - pgsql-marketplace
      - pgsql-keycloak

volumes:
  pgsqlconfMarketplace:
  pgsqldataMarketplace:
  pgsqldblogsMarketplace:
  pgsqlconfCadastro:
  pgsqldataCadastro:
  pgsqldblogsCadastro:
  pgsqlconfKeycloak:
  pgsqldataKeycloak:
  pgsqldblogsKeycloak:
  pgadmin4sessiondata:
  pgadmin4conf:
  pgadmin4serverdefinitions:

networks:
  default:
    external: true
    name: net-ifood