# Launch Elasticsearch
version: '3.9'

services:
  elasticsearch:
    container_name: elasticsearch-ifood
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    container_name: logstash-ifood
    image: docker.elastic.co/logstash/logstash:7.15.1
    volumes:
      - source: ./pipelines
        target: /usr/share/logstash/pipeline
        type: bind
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  # se ocorrer [1]: max virtual memory areas vm.max_map_count [65530] is too low, 
  # increase to at least [262144]
  # sudo sysctl -w vm.max_map_count=262144

  kibana:
    container_name: kibana-ifood
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    volumes:
      - kibana_yml_volume:/usr/share/kibana/config/
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  kibana_yml_volume:
    driver: local
  elasticsearch_volume:
    driver: local

networks:
  elk:
    driver: bridge